server {
  listen 80;
  root /usr/share/nginx/html;

  location / {
    try_files $uri $uri/ /index.html;
    add_header Cache-Control "no-cache, no-store, must-revalidate";
    add_header Pragma "no-cache";
    add_header Expires "0";
  }

  location ~* /api {
    proxy_pass https://recipes-service-360907376023.europe-north2.run.app;
  }

  location ~* /.(html|css|js)$ {
      expires -1;
  }

  location /health {
    access_log off;
    add_header 'Content-Type' 'application/json';
    return 200 '{"status":"UP"}';
  }
}