/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedWeeklyplanningRouteImport } from './routes/_authenticated.weeklyplanning'
import { Route as AuthenticatedShoppinglistRouteImport } from './routes/_authenticated.shoppinglist'
import { Route as AuthenticatedRecipesRouteImport } from './routes/_authenticated.recipes'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWeeklyplanningRoute =
  AuthenticatedWeeklyplanningRouteImport.update({
    id: '/weeklyplanning',
    path: '/weeklyplanning',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShoppinglistRoute =
  AuthenticatedShoppinglistRouteImport.update({
    id: '/shoppinglist',
    path: '/shoppinglist',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesRoute = AuthenticatedRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/shoppinglist': typeof AuthenticatedShoppinglistRoute
  '/weeklyplanning': typeof AuthenticatedWeeklyplanningRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/shoppinglist': typeof AuthenticatedShoppinglistRoute
  '/weeklyplanning': typeof AuthenticatedWeeklyplanningRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/recipes': typeof AuthenticatedRecipesRoute
  '/_authenticated/shoppinglist': typeof AuthenticatedShoppinglistRoute
  '/_authenticated/weeklyplanning': typeof AuthenticatedWeeklyplanningRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/recipes'
    | '/shoppinglist'
    | '/weeklyplanning'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/recipes'
    | '/shoppinglist'
    | '/weeklyplanning'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/recipes'
    | '/_authenticated/shoppinglist'
    | '/_authenticated/weeklyplanning'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/weeklyplanning': {
      id: '/_authenticated/weeklyplanning'
      path: '/weeklyplanning'
      fullPath: '/weeklyplanning'
      preLoaderRoute: typeof AuthenticatedWeeklyplanningRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shoppinglist': {
      id: '/_authenticated/shoppinglist'
      path: '/shoppinglist'
      fullPath: '/shoppinglist'
      preLoaderRoute: typeof AuthenticatedShoppinglistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes': {
      id: '/_authenticated/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthenticatedRecipesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedRecipesRoute: typeof AuthenticatedRecipesRoute
  AuthenticatedShoppinglistRoute: typeof AuthenticatedShoppinglistRoute
  AuthenticatedWeeklyplanningRoute: typeof AuthenticatedWeeklyplanningRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedRecipesRoute: AuthenticatedRecipesRoute,
  AuthenticatedShoppinglistRoute: AuthenticatedShoppinglistRoute,
  AuthenticatedWeeklyplanningRoute: AuthenticatedWeeklyplanningRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
