/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyplanningRouteImport } from './routes/weeklyplanning'
import { Route as ShoppinglistRouteImport } from './routes/shoppinglist'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as IndexRouteImport } from './routes/index'

const WeeklyplanningRoute = WeeklyplanningRouteImport.update({
  id: '/weeklyplanning',
  path: '/weeklyplanning',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppinglistRoute = ShoppinglistRouteImport.update({
  id: '/shoppinglist',
  path: '/shoppinglist',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recipes': typeof RecipesRoute
  '/shoppinglist': typeof ShoppinglistRoute
  '/weeklyplanning': typeof WeeklyplanningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipes': typeof RecipesRoute
  '/shoppinglist': typeof ShoppinglistRoute
  '/weeklyplanning': typeof WeeklyplanningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recipes': typeof RecipesRoute
  '/shoppinglist': typeof ShoppinglistRoute
  '/weeklyplanning': typeof WeeklyplanningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recipes' | '/shoppinglist' | '/weeklyplanning'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recipes' | '/shoppinglist' | '/weeklyplanning'
  id: '__root__' | '/' | '/recipes' | '/shoppinglist' | '/weeklyplanning'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipesRoute: typeof RecipesRoute
  ShoppinglistRoute: typeof ShoppinglistRoute
  WeeklyplanningRoute: typeof WeeklyplanningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weeklyplanning': {
      id: '/weeklyplanning'
      path: '/weeklyplanning'
      fullPath: '/weeklyplanning'
      preLoaderRoute: typeof WeeklyplanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoppinglist': {
      id: '/shoppinglist'
      path: '/shoppinglist'
      fullPath: '/shoppinglist'
      preLoaderRoute: typeof ShoppinglistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipesRoute: RecipesRoute,
  ShoppinglistRoute: ShoppinglistRoute,
  WeeklyplanningRoute: WeeklyplanningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
